apiVersion: v1
entries:
  registry:
  - apiVersion: v2
    appVersion: 0.2.0-M2-multi-tenancy
    created: "2022-10-06T16:21:37.1103821+02:00"
    dependencies:
    - condition: enablePostgres
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 11.1.9
    description: Tractus-X Digital Twin Registry Helm Chart
    digest: 5f4d1a3a1b8a91a7de730dbe7e930c5ca79959f9e6614a1bdee3321e65356a5d
    name: registry
    type: application
    urls:
    - registry/registry-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: 0.2.0-M2-multi-tenancy
    created: "2022-10-06T16:21:37.100276+02:00"
    dependencies:
    - condition: enablePostgres
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 11.1.9
    description: Tractus-X Digital Twin Registry Helm Chart
    digest: 6ce15ce36199e7504e9216c442b00e11b661c7b409062c2d746420b96804a249
    name: registry
    type: application
    urls:
    - registry/registry-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: 0.2.0-M1-multi-tenancy
    created: "2022-10-06T16:21:37.0892826+02:00"
    dependencies:
    - condition: enablePostgres
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 11.1.9
    description: A Helm chart for Kubernetes
    digest: 33e8ef76522843abb507d494be7267a639d58a3fb4e6aab76b6ccabe710a034a
    name: registry
    type: application
    urls:
    - registry/registry-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 0.1.0-M1-multi-tenancy
    created: "2022-10-06T16:21:37.078968+02:00"
    dependencies:
    - condition: enablePostgres
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 11.1.9
    description: A Helm chart for Kubernetes
    digest: 965d0e673566d12221ff342e775297dcd259218e1cf1bc9e0dd68fa1adbb618c
    name: registry
    type: application
    urls:
    - registry/registry-0.1.0.tgz
    version: 0.1.0
  semantic-hub:
  - apiVersion: v2
    appVersion: 0.1.0-M2
    created: "2022-10-06T16:21:37.127072+02:00"
    description: Helm Chart for the Catena-X Semantic Hub Application
    digest: 98e32c21a4e69bafb642af43312b7a440ad16fe868286311b6364670ada6a080
    name: semantic-hub
    type: application
    urls:
    - semantic-hub/semantic-hub-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.1.0-M2
    created: "2022-10-06T16:21:37.121541+02:00"
    description: Helm Chart for the Catena-X Semantic Hub Application
    digest: b7d0f87b5a10be9265fe870e1418c0e54b388e974671f27193436e7ad4c3d1e9
    name: semantic-hub
    type: application
    urls:
    - semantic-hub/semantic-hub-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.1.0-M1
    created: "2022-10-06T16:21:37.115967+02:00"
    description: Helm Chart for the Catena-X Semantic Hub Application
    digest: 8056fc7a7a0f8b9301e0969d27718ab87a2616633ab781a9ccdf60568aa420c8
    name: semantic-hub
    type: application
    urls:
    - semantic-hub/semantic-hub-0.1.0.tgz
    version: 0.1.0
generated: "2022-10-06T16:21:37.0677684+02:00"
